pinterest/urls.py
from django.contrib import admin
from django.urls import path, include

# to show the images
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('register', views.register_view, name='Signup'),
    path('login', views.login_view, name='Login'),
    path('username', views.username_view, name='username'),
    path('home/<user>', views.home_view, name='home'),
    path('profile/<user>', views.profile_view, name='profile'),
    path('createpin/<user>', views.createpin_view, name='createpin'),
    path('post/<postid>', views.postdetails_view, name='postdetails'),
    path('follow/<user>', views.follow_view, name='follow'),
]

users/models.py
from django.db import models
# Create your models here.


class Signup(models.Model):
    '''
    Table structure for newly added user
    '''

    user_id = models.AutoField(primary_key=True, null=False)
    user_name = models.CharField(max_length=200, null=False)
    user_email = models.CharField(max_length=200, null=False)
    user_password = models.CharField(max_length=200, null=False)
    user_age = models.IntegerField(null=False)

    def __str__(self):
        return str(self.user_name)


class Post(models.Model):
    '''
    Table structure for newly added post
    '''

    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(Signup, on_delete=models.CASCADE, null=False)
    user_name = models.CharField(max_length=200, null=False)
    user_post = models.FileField(upload_to='user_posts',
                                 null=False)  # for the image
    post_title = models.CharField(max_length=200)
    post_organise = models.CharField(max_length=200, null=True)
    post_topics = models.CharField(max_length=30, null=True)
    published_date = models.DateTimeField(auto_now_add=True, null=False)

    def __str__(self):
        return str(self.id)


class Save(models.Model):
    '''
    Table structure for saved post
    '''

    save_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(Signup, on_delete=models.CASCADE, null=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return str(self.post)


class Follow(models.Model):
    '''
    Table structure for follow user
    '''

    follow_id = models.AutoField(primary_key=True)
    # related_name is used to differentiate between both the users.
    follower = models.ForeignKey(
        Signup, on_delete=models.CASCADE, null=False, related_name='follower')
    following = models.ForeignKey(
        Signup, on_delete=models.CASCADE, null=False, related_name='following')

    def __str__(self):
        return str(self.follow_id)


class Comments(models.Model):
    '''
    Table structure for comments on post
    '''

    comment_id = models.AutoField(primary_key=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=False)
    name = models.ForeignKey(Signup, on_delete=models.CASCADE, null=False)
    comment = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True, null=False)

    def __str__(self):
        return str(self.comment_id)

users/views.py
from django.shortcuts import render, reverse
from .models import Signup, Post, Save, Follow, Comments
from django.http import HttpResponseRedirect
from datetime import date
from django.contrib.auth.models import User
from django.contrib.auth import logout, authenticate
from django.contrib import auth
# Create your views here.


######################  INDEX ##########################
def index_view(request):
    return render(request, 'index.html')


######################  REGISTER  ##########################
def register_view(request):
    '''
    Registering user when getting a post request and
    adding the user in the session and navigating to username.html file for further user details.

    Else if no post request has been made then return the register.html file.
    '''

    if request.method == 'POST':
        email = request.POST.get('email-re')
        password = request.POST.get('pass-re')
        age = int(request.POST.get('age'))

        # creating session of the email so that other pages can know which user it is.
        user_id = None
        user_id = Signup.objects.filter(user_email=email).values('user_id')

        if len(user_id) != 0:
            context = {
                'error': "User already exists !!!"
            }
            return render(request, 'register.html', context)

        else:
            request.session['user_email'] = email
            request.session['user_password'] = password
            request.session['user_age'] = age
            # to tell django that something has updated.
            # redirecting it to login form.
            return HttpResponseRedirect(reverse('users:username'))

    return render(request, 'register.html')


######################  USERNAME  ##########################
def username_view(request):
    '''
    Taking all the details passed throught the session and sending it to database.

    Else returning the username html file on request
    '''

    user_email = request.session.get('user_email')
    user_password = request.session.get('user_password')
    user_age = request.session.get('user_age')

    if request.method == 'POST':

        user_name = request.POST.get('username')
        request.session['user_name'] = user_name

        user = User.objects.create_user(
            username=user_name, password=user_password, email=user_email, first_name=user_name)
        user.save()

        new_user = Signup.objects.create(user_name=user_name, user_email=user_email,
                                         user_password=user_password, user_age=user_age)
        new_user.save()

        # getting the user_id and saving in session

        user_id = User.objects.get(email=user_email)
        request.session['user_id'] = user_id.id

        # deleting the not required sessions.
        try:
            request.session.pop('user_age')
            request.session.pop('user_password')
        except KeyError:
            pass

        return HttpResponseRedirect(reverse('users:home', kwargs={'user': user_name}))

    context = {
        'user_email': user_email,
        'user_password': user_password
    }
    return render(request, 'username.html', context)


######################  LOGIN  ##########################
def login_view(request):
    '''
    logging in the user by checking the db when post request is made.

    If no request is been made than returning the login page.
    '''

    if request.method == 'POST':

        email = request.POST.get('email')
        password = request.POST.get('pass')

        try:
            username = Signup.objects.get(user_email=email)
        except Signup.DoesNotExist:

            context = {
                'error': "Invalid Credentials !!!"
            }
            return render(request, 'login.html', context)

        user_name = username.user_name
        user = auth.authenticate(
            request, username=user_name, password=password)
        auth.login(request, user)
        user_id = Signup.objects.filter(user_email=email).values('user_id')
        user_id = user_id[0]['user_id']

        # checking if the users exists.

        user_name = None
        user_name = Signup.objects.filter(
            user_email=email).values('user_name')
        user_name = user_name[0]['user_name']

        request.session['user_id'] = user_id
        request.session['user_email'] = email
        request.session['user_name'] = user_name

        return HttpResponseRedirect(reverse('users:home', kwargs={'user': user_name}))

    return render(request, 'login.html')

######################  HOME  ##########################


def home_view(request, user):
    '''
    Return the username html file on request
    '''

    user_name = request.session.get('user_name')
    user_id = request.session.get('user_id')

    if request.method == 'POST':

        if 'save-post' in request.POST:

            # taking post and user id
            post_id = request.POST.get('post-id')
            user_id = request.session.get('user_id')

            # checking if it is present already in the database
            save_is_present = Save.objects.filter(
                user=user_id).filter(post=post_id)
            users_have_posted = Post.objects.filter(
                user=user_id).filter(id=post_id)

            # to save only that post which is not created by the same user.
            if len(save_is_present) == 0 and len(users_have_posted) == 0:
                id = Signup.objects.get(user_id=user_id)
                post = Post.objects.get(id=post_id)
                new_save = Save(user=id, post=post)
                new_save.save()

        else:
            logout(request)
            return HttpResponseRedirect(reverse('users:index'))

    try:
        request.session.pop('postid')
    except KeyError:
        pass

    posts = Post.objects.all().order_by('-published_date')
    user = user_name
    context = {
        'user_name': user_name,
        'posts': posts,
        'user_id': user_id,
    }
    return render(request, 'home.html', context)


######################  PROFILE  ##########################
def profile_view(request, user):
    '''
    Return the profile.html file on request and sending the context.
    '''

    if user != str(request.user) and 'postid' in request.session:

        user_post = Post.objects.all().filter(id=request.session['postid'])
        user_follow = None
        for other_user in user_post:
            user_follow = other_user.user_id

        other_user_details = Signup.objects.get(user_id=user_follow)
        id = other_user_details.user_id
        name = other_user_details.user_name
        email = other_user_details.user_email
        post = Post.objects.all().filter(user=other_user_details.user_id)

        user_id = Signup.objects.get(user_id=request.user.id)

        check_following = Follow.objects.filter(
            follower=user_id, following=id)

        check_following = len(check_following)

        follow_count = Follow.objects.filter(following=id).count()
        following_count = Follow.objects.filter(follower=id).count()

        saved_post = Save.objects.filter(user=id)

        context = {
            'id': id,
            'already_followed': check_following,
            'posts': post,
            'user_email': email,
            'user_name': name,
            'follow_count': follow_count,
            'following_count': following_count,
            'savedpost': saved_post
        }
        user = name
        return render(request, 'profile.html', context)

    else:
        try:
            request.session.pop('postid')
        except KeyError:
            pass

        posts = Post.objects.all().filter(user_id=request.session.get('user_id'))
        user_email = request.session['user_email']
        user_name = request.session['user_name']
        follow_count = Follow.objects.filter(following=request.user.id).count()
        following_count = Follow.objects.filter(
            follower=request.user.id).count()

        saved_post = Save.objects.filter(user=request.user.id)

        context = {
            'user_email': user_email,
            'user_name': user_name,
            'posts': posts,
            'follow_count': follow_count,
            'following_count': following_count,
            'savedpost': saved_post
        }
        return render(request, 'profile.html', context)


######################  CREATEPIN  ##########################
def createpin_view(request, user):
    '''
    Made for creating the pins(posting images.)
    '''

    try:
        request.session.pop('postid')
    except KeyError:
        pass

    if request.method == 'POST':
        id = Signup.objects.get(user_id=request.session.get('user_id'))
        post = request.FILES.get('image-file')
        title = request.POST.get('title')
        organise = request.POST.get('organise')
        topics = request.POST.get('topics')
        name = request.session.get('user_name')

        # checking if the organise field is empty or not and saving it accordingly.
        if organise != None:

            if topics != None:
                new_post = Post(user=id, user_name=name, user_post=post, post_title=title,
                                post_organise=organise, post_topics=topics)
                new_post.save()
                return HttpResponseRedirect(reverse('users:profile', kwargs={'user': name}))

            else:
                new_post = Post(user=id, user_name=name, user_post=post, post_title=title,
                                post_organise=organise)
                new_post.save()
                return HttpResponseRedirect(reverse('users:profile', kwargs={'user': name}))

        else:
            new_post = Post(user=id, user_name=name,
                            user_post=post, post_title=title)
            new_post.save()
            return HttpResponseRedirect(reverse('users:profile', kwargs={'user': name}))

    user_id = request.session['user_id']

users/templates/createpin.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
<!------------------------------------------------------ CREATE SECTION ----------------------------------------------------->
<form action="{% url 'users:createpin' user=user_name%}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" id="myFile" name="image-file" required>
    <br>
    <h4>Add the basics</h4>
    <p>Idea pin title
    <p>
        <input type="text" placeholder="Add title" name="title">
    <p>Organise on a board</p>
    <input type="text" name="organise">

    <p>Tagged topics</p>
    <input type="Search for a tag" name="topic">

    <p>Don't worry, people won't see your tags</p>

    <input type="submit">
</form>
{% endblock %}

users/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <script src="https://kit.fontawesome.com/716d1f19dd.js" crossorigin="anonymous"></script>
    <title>Pinterest</title>
</head>

<body>

    <!------------------------------------------------------ HEADER SECTION ----------------------------------------------------->
    <header>
        <div class="navbar-container">
            <div class="navbar">
                <div class="components-container">
                    <div class="logo-container">
                        <img src="{% static 'images/Pinterest-Logo.png' %}">
                    </div>
                    <div class="text-container">
                        <div class="navigations">
                            <ul>
                                <li id="drop-down" class="hide"> Home <i class="fa-solid fa-chevron-down"></i></li>
                                <div class="dropdown-content" id="drop">
                                    <a href="{% url 'users:home' user=user_name %}">
                                        <li><button id="home" class="active">Home</button></li>
                                    </a>
                                    <a href="#">
                                        <li><button id="today">Today</button></li>
                                    </a>
                                    <a href="{% url 'users:createpin' user=user_name %}">
                                        <li><button id="create">Create <i class="fa-solid fa-chevron-down"></i></button>
                                        </li>
                                    </a>
                                </div>
                            </ul>
                        </div>
                        <div class="search-box-container">
                            <input type="text" placeholder="Search" name="search">
                            <i id="icon" class="fa-solid fa-magnifying-glass"></i>
                        </div>
                        <div class="other-icons-container">
                            <div class="icons-container">
                                <div class="bell-icon">
                                    <i id="icon1" class="fa fa-bell"></i>
                                </div>
                                <div class="chat-icon">
                                    <i id="icon2" class='far fa-comment-dots'></i>
                                </div>
                                <div class="user-icon">
                                    <a href="{% url 'users:profile' user=request.user %}"> <i id="icon3"
                                            class="fas fa-user-circle "></i></a>
                                </div>

                                <div class="drop-down-icon">
                                    <i id="other-options" class="fa-solid fa-chevron-down"></i>
                                    <div class="dropdown-content2" id="drop2">
                                        <form action="{% url 'users:home' user=user_name %}" method="POST">
                                            {% csrf_token %}
                                            <button type="submit" value="logout-user">Log out</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% block content %}

    <!------------------------------------------------------ ALL POSTS SECTION ----------------------------------------------------->
    <section class="all-posts">
        <div class="posts-container">
            <div class="posts">
                {% for post in posts %}
                {% if forloop.counter0|divisibleby:4 %}
                <div class="user-posts-4">
                    <form action="{% url 'users:home' user=user_name%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{post.id}}" name="post-id">
                        <a href="/post/{{post.id}}"><img class="post-image" src="{{post.user_post.url}}"></a>
                        <button class="post-button" name='save-post' type="submit">Save</button>
                    </form>
                </div>
                {% elif forloop.counter|divisibleby:3 %}
                <div class="user-posts-3">
                    <form action="{% url 'users:home' user=user_name%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{post.id}}" name="post-id">
                        <a href="/post/{{post.id}}"><img class="post-image" src="{{post.user_post.url}}"></a>
                        <button class="post-button" name='save-post' type="submit">Save</button>
                    </form>
                </div>
                {% elif forloop.counter|divisibleby:2 %}
                <div class="user-posts-2">
                    <form action="{% url 'users:home' user=user_name%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{post.id}}" name="post-id">
                        <a href="/post/{{post.id}}"><img class="post-image" src="{{post.user_post.url}}"></a>
                        <button class="post-button" name='save-post' type="submit">Save</button>
                    </form>
                </div>
                {% else %}
                <div class="user-posts-1">
                    <form action="{% url 'users:home' user=user_name%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{post.id}}" name="post-id">
                        <a href="/post/{{post.id}}"><img class="post-image" src="{{post.user_post.url}}"></a>
                        <button class="post-button" name='save-post' type="submit">Save</button>
                    </form>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </section>
    {% endblock %}
    <script src="{% static 'js/home.js' %}"></script>
    <script>
        var counter = 0;
        function getSeconds() {

            let windowWidth = window.innerWidth;
            if (windowWidth >= 550 && counter === 0) {
                // $('.icon').addClass('fa-xl');
                document.getElementById('icon').className += ' fa-xl';
                document.getElementById('icon1').className += ' fa-xl';
                document.getElementById('icon2').className += ' fa-xl';
                document.getElementById('icon3').className += ' fa-xl';
                counter += 1;
            } else if (counter === 1) {
                // $('i').removeClass('fa-xl');
                // document.getElementById('icon').className.remove(' fa-xl');
                // document.getElementById('icon1').className.remove(' fa-xl');
                // document.getElementById('icon2').className.remove(' fa-xl');
                // document.getElementById('icon3').className.remove(' fa-xl');
                counter -= 1;
            }
        }
        setInterval(getSeconds, 1000);

    </script>
</body>

</html>

users/templates/login.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<!------------------------------------------------------ LOGIN SECTION ----------------------------------------------------->
<div id="log-form" class="user-login">
    <div class="login-container">
        <div class="login-form">
            <div class="button-cancel-1">
                <a href="/"><span id="close">&times;</span></a>
            </div>
            <div class="login-form-container">
                <form id="form1" action="/login" method="POST">
                    {% csrf_token %}
                    {{error}}
                    <div class="logo">
                        <img src="{% static 'images/Pinterest-Logo.png' %}">
                    </div>
                    <h3>Welcome to Pinterest</h3>
                    <div class="input-div-area-login">
                        <div class="login-input-area">
                            <label>Email address</label><br>
                            <input id="email-login" type="email" placeholder="Email address" name="email" required>
                            <p id="login-email-error">Hmm...that doesn't look like an email address</p>
                        </div>
                        <div class="login-input-area">
                            <label>Password</label><br>
                            <input id="password-login" type="password" placeholder="Password" name="pass" required>
                            <p id="login-password-error">Your password is too short. It needs to be 6+
                                characters.</p>
                        </div>
                    </div>
                    <p>Forgotten your password?</p>
                    <div>
                        <button type="submit" id="continue-login">Log in</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/profile.html
{% extends 'home.html' %}
{% load staticfiles %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/profile.css' %}">

<!------------------------------------------------------ PROFILE SECTION ----------------------------------------------------->
<div class="profile-container">
    <div class="image-container">
        <img src="../static/images/user.jpeg">
    </div>
    <div class="user-details">
        <h1>{{user_name}}</h1>
        <h4>{{user_email}}</h4>
        <div class="user-buttons">
            {% if id %}
            <p>{{follow_count}} follower . {{following_count}} following</p>
            <button>Message</button>
            {% if already_followed == 0 %}
            <a href="/follow/{{user_name}}"><button class="follow">Follow</button></a>
            {% else %}
            <a href="/follow/{{user_name}}"><button class="unfollow">Following</button></a>
            {% endif %}
            {% else %}
        </div>
        <button class="share">Share</button>
        <button>Edit Profile</button>
        {% endif %}
    </div>
    <div class="pins-container">
        <ul>
            <li id="user-created">Created</li>
            <li id="user-saved">Saved</li>

        </ul>
    </div>

    <div id="user-created-pins" class="created-user-posts">
        {% if posts %}
        <div class="posts-container">
            <div class="posts">
                {% for post in posts %}
                {% if forloop.counter|divisibleby:4 %}
                <div class="user-posts-4">
                    <form action="{% url 'users:home' user=user_name%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{post.id}}" name="post-id">
                        <a href="/post/{{post.id}}"><img class="post-image" src="{{post.user_post.url}}"></a>
                        <button class="post-button" name='save-post' type="submit">Save</button>
                    </form>
                </div>
                {% elif forloop.counter|divisibleby:3 %}
                <div class="user-posts-3">
                    <form action="{% url 'users:home' user=user_name%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{post.id}}" name="post-id">
                        <a href="/post/{{post.id}}"><img class="post-image" src="{{post.user_post.url}}"></a>
                    </form>
                </div>
                {% elif forloop.counter|divisibleby:2 %}
                <div class="user-posts-2">
                    <form action="{% url 'users:home' user=user_name%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{post.id}}" name="post-id">
                        <a href="/post/{{post.id}}"><img class="post-image" src="{{post.user_post.url}}"></a>
                    </form>
                </div>
                {% else %}
                <div class="user-posts-1">
                    <form action="{% url 'users:home' user=user_name%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{post.id}}" name="post-id">
                        <a href="/post/{{post.id}}"><img class="post-image" src="{{post.user_post.url}}"></a>
                    </form>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% else %}
        <div class="created-post-context">
            <strong>
                <p>Inspire with an Idea Pin</p>
            </strong>
            <a href="{% url 'users:createpin' user=user_name %}"><button> Create </button></a>
        </div>
        {% endif %}
    </div>
    <div id="user-saved-pins" class="saved-post">
        {% if savedpost %}

        <div class="posts-container">
            <div class="posts">
                {% for saved in savedpost %}
                {% if forloop.counter|divisibleby:4 %}
                <div class="user-posts-4">
                    <form action="{% url 'users:home' user=user_name%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{post.id}}" name="post-id">
                        <a href="/post/{{saved.post.id}}"><img class="post-image"
                                src="{{saved.post.user_post.url}}"></a>
                    </form>
                </div>
                {% elif forloop.counter|divisibleby:3 %}
                <div class="user-posts-3">
                    <form action="{% url 'users:home' user=user_name%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{post.id}}" name="post-id">
                        <a href="/post/{{saved.post.id}}"><img class="post-image"
                                src="{{saved.post.user_post.url}}"></a>
                    </form>
                </div>
                {% elif forloop.counter|divisibleby:2 %}
                <div class="user-posts-2">
                    <form action="{% url 'users:home' user=user_name%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{post.id}}" name="post-id">
                        <a href="/post/{{saved.post.id}}"><img class="post-image"
                                src="{{saved.post.user_post.url}}"></a>
                    </form>
                </div>
                {% else %}
                <div class="user-posts-1">
                    <form action="{% url 'users:home' user=user_name%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{post.id}}" name="post-id">
                        <a href="/post/{{saved.post.id}}"><img class="post-image"
                                src="{{saved.post.user_post.url}}"></a>
                    </form>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% else %}
        <div class="saved-post-context">
            <p>You haven't saved any Pins yet</p>
            <a href="{% url 'users:home' user=user_name %}"><button>Find ideas</button></a>
        </div>
        {% endif %}
    </div>
</div>
<script src="{% static 'js/profile.js' %}"></script>
{% endblock %}